// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'jobparttemplatedetail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

JobPartTemplateDetail _$JobPartTemplateDetailFromJson(
        Map<String, dynamic> json) =>
    JobPartTemplateDetail(
      job_part_template_id: (json['job_part_template_id'] as num?)?.toInt(),
      col1: json['col1'] as String?,
      col2: json['col2'] as String?,
      col3: json['col3'] as String?,
      col4: json['col4'] as String?,
      col5: json['col5'] as String?,
      col6: json['col6'] as String?,
      col7: json['col7'] as String?,
      col8: json['col8'] as String?,
      col9: json['col9'] as String?,
      col10: json['col10'] as String?,
      col11: json['col11'] as String?,
      col12: json['col12'] as String?,
      col13: json['col13'] as String?,
      col14: json['col14'] as String?,
      col15: json['col15'] as String?,
      col16: json['col16'] as String?,
      col17: json['col17'] as String?,
      col18: json['col18'] as String?,
      col19: json['col19'] as String?,
      col20: json['col20'] as String?,
      col21: json['col21'] as String?,
      col22: json['col22'] as String?,
      col23: json['col23'] as String?,
      col24: json['col24'] as String?,
      col25: json['col25'] as String?,
      col26: json['col26'] as String?,
      col27: json['col27'] as String?,
      col28: json['col28'] as String?,
      col29: json['col29'] as String?,
      col30: json['col30'] as String?,
      col31: json['col31'] as String?,
      col32: json['col32'] as String?,
      col33: json['col33'] as String?,
      col34: json['col34'] as String?,
      col35: json['col35'] as String?,
      col36: json['col36'] as String?,
      col37: json['col37'] as String?,
      col38: json['col38'] as String?,
      col39: json['col39'] as String?,
      col40: json['col40'] as String?,
      col41: json['col41'] as String?,
      col42: json['col42'] as String?,
      col43: json['col43'] as String?,
      col44: json['col44'] as String?,
      col45: json['col45'] as String?,
      col46: json['col46'] as String?,
      col47: json['col47'] as String?,
      col48: json['col48'] as String?,
      col49: json['col49'] as String?,
      col50: json['col50'] as String?,
      col51: json['col51'] as String?,
      col52: json['col52'] as String?,
      col53: json['col53'] as String?,
      col54: json['col54'] as String?,
      col55: json['col55'] as String?,
      col56: json['col56'] as String?,
      col57: json['col57'] as String?,
      col58: json['col58'] as String?,
      col59: json['col59'] as String?,
      col60: json['col60'] as String?,
      col61: json['col61'] as String?,
      col62: json['col62'] as String?,
      col63: json['col63'] as String?,
      col64: json['col64'] as String?,
      col65: json['col65'] as String?,
      col66: json['col66'] as String?,
      col67: json['col67'] as String?,
      col68: json['col68'] as String?,
      col69: json['col69'] as String?,
      col70: json['col70'] as String?,
      col71: json['col71'] as String?,
      col72: json['col72'] as String?,
      col73: json['col73'] as String?,
      col74: json['col74'] as String?,
      col75: json['col75'] as String?,
      col76: json['col76'] as String?,
      col77: json['col77'] as String?,
      col78: json['col78'] as String?,
      col79: json['col79'] as String?,
      col80: json['col80'] as String?,
    );

Map<String, dynamic> _$JobPartTemplateDetailToJson(
        JobPartTemplateDetail instance) =>
    <String, dynamic>{
      'job_part_template_id': instance.job_part_template_id,
      'col1': instance.col1,
      'col2': instance.col2,
      'col3': instance.col3,
      'col4': instance.col4,
      'col5': instance.col5,
      'col6': instance.col6,
      'col7': instance.col7,
      'col8': instance.col8,
      'col9': instance.col9,
      'col10': instance.col10,
      'col11': instance.col11,
      'col12': instance.col12,
      'col13': instance.col13,
      'col14': instance.col14,
      'col15': instance.col15,
      'col16': instance.col16,
      'col17': instance.col17,
      'col18': instance.col18,
      'col19': instance.col19,
      'col20': instance.col20,
      'col21': instance.col21,
      'col22': instance.col22,
      'col23': instance.col23,
      'col24': instance.col24,
      'col25': instance.col25,
      'col26': instance.col26,
      'col27': instance.col27,
      'col28': instance.col28,
      'col29': instance.col29,
      'col30': instance.col30,
      'col31': instance.col31,
      'col32': instance.col32,
      'col33': instance.col33,
      'col34': instance.col34,
      'col35': instance.col35,
      'col36': instance.col36,
      'col37': instance.col37,
      'col38': instance.col38,
      'col39': instance.col39,
      'col40': instance.col40,
      'col41': instance.col41,
      'col42': instance.col42,
      'col43': instance.col43,
      'col44': instance.col44,
      'col45': instance.col45,
      'col46': instance.col46,
      'col47': instance.col47,
      'col48': instance.col48,
      'col49': instance.col49,
      'col50': instance.col50,
      'col51': instance.col51,
      'col52': instance.col52,
      'col53': instance.col53,
      'col54': instance.col54,
      'col55': instance.col55,
      'col56': instance.col56,
      'col57': instance.col57,
      'col58': instance.col58,
      'col59': instance.col59,
      'col60': instance.col60,
      'col61': instance.col61,
      'col62': instance.col62,
      'col63': instance.col63,
      'col64': instance.col64,
      'col65': instance.col65,
      'col66': instance.col66,
      'col67': instance.col67,
      'col68': instance.col68,
      'col69': instance.col69,
      'col70': instance.col70,
      'col71': instance.col71,
      'col72': instance.col72,
      'col73': instance.col73,
      'col74': instance.col74,
      'col75': instance.col75,
      'col76': instance.col76,
      'col77': instance.col77,
      'col78': instance.col78,
      'col79': instance.col79,
      'col80': instance.col80,
    };
