// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'jobparttemplates.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

JobPartTemplates _$JobPartTemplatesFromJson(Map<String, dynamic> json) =>
    JobPartTemplates(
      (json['id'] as num).toInt(),
      (json['job_part_id'] as num?)?.toInt(),
      (json['template_id'] as num?)?.toInt(),
      json['col1'] as String?,
      json['col2'] as String?,
      json['col3'] as String?,
      json['col4'] as String?,
      json['col5'] as String?,
      json['col6'] as String?,
      json['col7'] as String?,
      json['col8'] as String?,
      json['col9'] as String?,
      json['col10'] as String?,
      json['col11'] as String?,
      json['col12'] as String?,
      json['col13'] as String?,
      json['col14'] as String?,
      json['col15'] as String?,
      json['col16'] as String?,
      json['col17'] as String?,
      json['col18'] as String?,
      json['col19'] as String?,
      json['col20'] as String?,
      json['col21'] as String?,
      json['col22'] as String?,
      json['col23'] as String?,
      json['col24'] as String?,
      json['col25'] as String?,
      json['col26'] as String?,
      json['col27'] as String?,
      json['col28'] as String?,
      json['col29'] as String?,
      json['col30'] as String?,
      json['checked'] as bool?,
      json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
      json['updated_at'] == null
          ? null
          : DateTime.parse(json['updated_at'] as String),
      json['template'] == null
          ? null
          : Template.fromJson(json['template'] as Map<String, dynamic>),
      json['col31'] as String?,
      json['col32'] as String?,
      json['col33'] as String?,
      json['col34'] as String?,
      json['col35'] as String?,
      json['col36'] as String?,
      json['col37'] as String?,
      json['col38'] as String?,
      json['col39'] as String?,
      json['col40'] as String?,
      json['col41'] as String?,
      json['col42'] as String?,
      json['col43'] as String?,
      json['col44'] as String?,
      json['col45'] as String?,
      json['col46'] as String?,
      json['col47'] as String?,
      json['col49'] as String?,
      json['col50'] as String?,
      json['col51'] as String?,
      json['col52'] as String?,
      json['col53'] as String?,
      json['col54'] as String?,
      json['col55'] as String?,
      json['col56'] as String?,
      json['col57'] as String?,
      json['col58'] as String?,
      json['col59'] as String?,
      json['col60'] as String?,
      json['col61'] as String?,
      json['col62'] as String?,
      json['col63'] as String?,
      json['col64'] as String?,
      json['col65'] as String?,
      json['col66'] as String?,
      json['col67'] as String?,
      json['col68'] as String?,
      json['col69'] as String?,
      json['col70'] as String?,
      json['col48'] as String?,
      json['col71'] as String?,
      json['col72'] as String?,
      json['col73'] as String?,
      json['col74'] as String?,
      json['col75'] as String?,
      json['col76'] as String?,
      json['col77'] as String?,
      json['col78'] as String?,
      json['col79'] as String?,
      json['col80'] as String?,
    );

Map<String, dynamic> _$JobPartTemplatesToJson(JobPartTemplates instance) =>
    <String, dynamic>{
      'id': instance.id,
      'job_part_id': instance.job_part_id,
      'template_id': instance.template_id,
      'col1': instance.col1,
      'col2': instance.col2,
      'col3': instance.col3,
      'col4': instance.col4,
      'col5': instance.col5,
      'col6': instance.col6,
      'col7': instance.col7,
      'col8': instance.col8,
      'col9': instance.col9,
      'col10': instance.col10,
      'col11': instance.col11,
      'col12': instance.col12,
      'col13': instance.col13,
      'col14': instance.col14,
      'col15': instance.col15,
      'col16': instance.col16,
      'col17': instance.col17,
      'col18': instance.col18,
      'col19': instance.col19,
      'col20': instance.col20,
      'col21': instance.col21,
      'col22': instance.col22,
      'col23': instance.col23,
      'col24': instance.col24,
      'col25': instance.col25,
      'col26': instance.col26,
      'col27': instance.col27,
      'col28': instance.col28,
      'col29': instance.col29,
      'col30': instance.col30,
      'col31': instance.col31,
      'col32': instance.col32,
      'col33': instance.col33,
      'col34': instance.col34,
      'col35': instance.col35,
      'col36': instance.col36,
      'col37': instance.col37,
      'col38': instance.col38,
      'col39': instance.col39,
      'col40': instance.col40,
      'col41': instance.col41,
      'col42': instance.col42,
      'col43': instance.col43,
      'col44': instance.col44,
      'col45': instance.col45,
      'col46': instance.col46,
      'col47': instance.col47,
      'col48': instance.col48,
      'col49': instance.col49,
      'col50': instance.col50,
      'col51': instance.col51,
      'col52': instance.col52,
      'col53': instance.col53,
      'col54': instance.col54,
      'col55': instance.col55,
      'col56': instance.col56,
      'col57': instance.col57,
      'col58': instance.col58,
      'col59': instance.col59,
      'col60': instance.col60,
      'col61': instance.col61,
      'col62': instance.col62,
      'col63': instance.col63,
      'col64': instance.col64,
      'col65': instance.col65,
      'col66': instance.col66,
      'col67': instance.col67,
      'col68': instance.col68,
      'col69': instance.col69,
      'col70': instance.col70,
      'col71': instance.col71,
      'col72': instance.col72,
      'col73': instance.col73,
      'col74': instance.col74,
      'col75': instance.col75,
      'col76': instance.col76,
      'col77': instance.col77,
      'col78': instance.col78,
      'col79': instance.col79,
      'col80': instance.col80,
      'checked': instance.checked,
      'created_at': instance.created_at?.toIso8601String(),
      'updated_at': instance.updated_at?.toIso8601String(),
      'template': instance.template,
    };
